################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../app.c \
../application_properties.c \
../gatt_db.c \
../init_app.c \
../init_board.c \
../init_mcu.c \
../main.c \
../pti.c 

OBJS += \
./app.o \
./application_properties.o \
./gatt_db.o \
./init_app.o \
./init_board.o \
./init_mcu.o \
./main.o \
./pti.o 

C_DEPS += \
./app.d \
./application_properties.d \
./gatt_db.d \
./init_app.d \
./init_board.d \
./init_mcu.d \
./main.d \
./pti.d 


# Each subdirectory must supply rules for building sources it contributes
app.o: ../app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\CMSIS\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\bsp" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\drivers" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\halconfig" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\app\bluetooth\common\util" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\uartdrv\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader\api" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ble" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\common\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\halconfig\inc\hal-config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"app.d" -MT"app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

application_properties.o: ../application_properties.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\CMSIS\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\bsp" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\drivers" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\halconfig" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\app\bluetooth\common\util" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\uartdrv\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader\api" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ble" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\common\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\halconfig\inc\hal-config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"application_properties.d" -MT"application_properties.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gatt_db.o: ../gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\CMSIS\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\bsp" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\drivers" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\halconfig" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\app\bluetooth\common\util" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\uartdrv\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader\api" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ble" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\common\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\halconfig\inc\hal-config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"gatt_db.d" -MT"gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_app.o: ../init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\CMSIS\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\bsp" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\drivers" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\halconfig" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\app\bluetooth\common\util" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\uartdrv\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader\api" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ble" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\common\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\halconfig\inc\hal-config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_app.d" -MT"init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_board.o: ../init_board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\CMSIS\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\bsp" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\drivers" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\halconfig" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\app\bluetooth\common\util" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\uartdrv\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader\api" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ble" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\common\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\halconfig\inc\hal-config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_board.d" -MT"init_board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_mcu.o: ../init_mcu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\CMSIS\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\bsp" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\drivers" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\halconfig" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\app\bluetooth\common\util" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\uartdrv\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader\api" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ble" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\common\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\halconfig\inc\hal-config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_mcu.d" -MT"init_mcu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\CMSIS\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\bsp" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\drivers" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\halconfig" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\app\bluetooth\common\util" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\uartdrv\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader\api" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ble" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\common\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\halconfig\inc\hal-config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"main.d" -MT"main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pti.o: ../pti.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__StackLimit=0x20000000' '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DEFR32BG13P632F512GM48=1' -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\CMSIS\Include" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\bsp" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\sleep\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\drivers" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\common\halconfig" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\src" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\app\bluetooth\common\util" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\common" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emlib\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\uartdrv\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\hardware\kit\EFR32BG13_BRD4104A\config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader\api" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\protocol\ble" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\emdrv\common\inc" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\halconfig\inc\hal-config" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\satya\SimplicityStudio\v4_workspace\shopping_cart\platform\bootloader" -O0 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pti.d" -MT"pti.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


